# Site Ayarları
title: LaTeX Ders Notları
description: >-
  Mühendislik öğrencileri için Overleaf üzerinden LaTeX ders notları ve kaynakları.
baseurl: "/LaTex-Dersleri" # Deponuzun adı
url: "https://ferahfeza.github.io" # GitHub kullanıcı adınız
github_username: ferahfeza

# Jekyll Tema Ayarları
theme: jekyll-theme-minimal

# Eklentiler
plugins:
  - jekyll-feed